toggle:
  fields:
    zone:
      description: "the zone you want to update (number)"
      example: 1
      required: true
      selector:
        number:
          min: 1
          max: 5
          step: 1
    type:
      description: "the type of toggle (state or mode)"
      example: "state"
      required: true
      default: state
      selector:
        select:
          options:
            - value: "state"
              label: "State"
            - value: "mode"
              label: "Mode"
