toggle:
  fields:
    zone:
      example: 1
      required: true
      selector:
        number:
          min: 1
          max: 5
          step: 1
    type:
      example: "state"
      required: true
      default: state
      selector:
        select:
          translation_key: "type"
          options:
            - state
            - mode
